### ISSUE TITLE
[WEBSITE FEEDBACK] Add new click to copy and display hex values always.

### ISSUE THREAD

**Issue by bohl3r** [brandcolors/feedback#279]
The ability to click to copy would be an amazing addition to the BrandColors website. Although, I do love the ability to "bundle" colors and download them - a site like this needs to have a copy and paste function. Maybe also always display HEX values for color (if possible, I know some brands have a ton of colors).

**Comment by galengidman** [comment]
Click to copy is something that has been brought up a lot. The issue is that from a technical perspective, the only way to implement it is to Flash, and hundreds of Flash movies really slow down the page. We've tried it, but performance always takes a major hit. I'd be super open to any other suggestions for how to make it easier to access the hex values though.

**Comment by bgiesing** [comment]
@galengidman It's now a part of HTML5 Spec: https://developers.google.com/web/updates/2015/04/cut-and-copy-commands?hl=en

**Comment by galengidman** [comment]
@bgiesing !!!

This'll be coming in the next version.
