### ISSUE TITLE
PJ's Pour House

### ISSUE THREAD

**Issue by pjwrestaurantgroup** [brandcolors/feedback#500]
- [x] *PJ's Pour House*:
- [x] *a39161,8b0f04,000005,faa61a*:
- [x] *www.PJsPourHouse.com*:
- [ ] *Updating brand* 
- [x] *Creator*:

**Comment by pjwrestaurantgroup** [comment]
How does this get posted??

**Comment by dkhamsing** [comment]
see #499

**Comment by galengidman** [comment]
Thanks for taking the time to submit. To have brands added to the website, we must manually add them ourselves. Creating an issue here on GitHub doesn't automatically do it.

Since these are local/very small chain restaurants, I'm going to hold off adding them for now. Not sure they're really the type of brand that would be helpful to have on the website. Thanks again for taking the time to submit though!
